### ISSUE TITLE
Acceso al Geoserver

### ISSUE THREAD

**Issue by jormaral** [jormaral/urbanismo#39]
He realizado la instalación de la Consola de UeR siguiendo el manual URBR-CON_2011_12_Manual_Instalacion_v006 pero no consigo acceder al GeoServer desde la dirección <IP_DEL_SERVIDOR>:8080/geoserver porque el recurso no está disponible.

En el manual de instalación URBR-CON_2011_12_Manual_Instalacion_2_NODO_v01 el puerto del geoserver que indican es el 8081, pero tampoco accedo.

He comprobado que en el JBOSS el geoserver.war está activo. 

En el servidor donde estoy realizando la instalación, he realizado los pasos que indica el manual para instalar GeoServer. Adjunto en un archivo TXT los comando ejecutados.

¿Cuál puede ser el motivo por el que no puedo acceder a GeoServer? ¿Es necesario modificar algún parámetro del .war?

Muchas gracias.
Un saludo.
[Geoserver.txt](https://github.com/jormaral/urbanismo/files/191658/Geoserver.txt)

**Comment by jormaral** [comment]
Buenas de nuevo Coral, 

como te he comentado el manual a seguir es de _v006, ¿has reiciado el servidor y sigue sin funcionar? Geoserver debe responder en el puerto 8080:

http://<IP_DEL_SERVIDOR>:8080/geoserver

Si sigue sin funcionar necesitaríamos comprobar qué error está dando en el log de JBOSS : /urbr/app/jboss7/standalone/log/server.log

Un saludo.

**Comment by jormaral** [comment]
Buenos días.

He comprobado el log y al final aparece un mensaje como este:
10:54:44,652 ERROR [org.apache.catalina.core.StandardContext](MSC service thread 1-2) Falló en arranque del Contexto [/geoserver] debido a errores previos

Hay muchos mensajes de información, un error previo, y bastantes WARN.

El error previo es:
10:54:15,076 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/geoserver]](MSC service thread 1-2) Excepción enviando evento inicializado de contexto a instancia de escuchador de clase org.geoserver.GeoserverInitStartupListener: ```
java.util.ServiceConfigurationError: javax.imageio.spi.ImageOutputStreamSpi: Provider com.sun.media.imageioimpl.stream.ChannelImageOutputStreamSpi could not be instantiated: java.lang.IllegalArgumentException: vendorName == null!
at java.util.ServiceLoader.fail(ServiceLoader.java:224) [:1.7.0_02]
at java.util.ServiceLoader.access$100(ServiceLoader.java:181) [:1.7.0_02]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:370) [:1.7.0_02]
at java.util.ServiceLoader$1.next(ServiceLoader.java:438) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159) [:1.7.0_02]
at javax.imageio.ImageIO.<clinit>(ImageIO.java:65) [:1.7.0_02]
at org.geoserver.GeoserverInitStartupListener.contextInitialized(GeoserverInitStartupListener.java:107) [main-2.4.0.jar:]
at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3368) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
at org.apache.catalina.core.StandardContext.start(StandardContext.java:3821) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:70) [jboss-as-web-7.0.2.Final.jar:7.0.2.Final]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1824)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1759)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [:1.7.0_02]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [:1.7.0_02]
at java.lang.Thread.run(Thread.java:722) [:1.7.0_02]
Caused by: java.lang.IllegalArgumentException: vendorName == null!
at javax.imageio.spi.IIOServiceProvider.<init>(IIOServiceProvider.java:76) [:1.7.0_02]
at javax.imageio.spi.ImageOutputStreamSpi.<init>(ImageOutputStreamSpi.java:91) [:1.7.0_02]
at com.sun.media.imageioimpl.stream.ChannelImageOutputStreamSpi.<init>(ChannelImageOutputStreamSpi.java:64) [jai_imageio-1.1.jar:]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [:1.7.0_02]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [:1.7.0_02]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [:1.7.0_02]
at java.lang.reflect.Constructor.newInstance(Constructor.java:525) [:1.7.0_02]
at java.lang.Class.newInstance0(Class.java:372) [:1.7.0_02]
at java.lang.Class.newInstance(Class.java:325) [:1.7.0_02]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:362) [:1.7.0_02]
... 14 more

```


Y los mensajes de WARN, que hay unos 1000 aproximadamente son como este:
10:54:08,855 WARN [org.jboss.as.server.deployment] (MSC service thread 1-2) Class Path entry jgridshift-1.0.jar in "/content/geoserver.war/WEB-INF/lib/gt-referencing-10.0.jar" does not point to a valid jar for a Class-Path reference.

Cambia el Class Path entry y el archivo .jar.

Muchas gracias.
```

**Comment by jormaral** [comment]
Buenos dias Coral,

Ese error que te está dando es porque no estás utlizando el geoserver que está en la carpeta software. Prueba a cambiar el gesoerver.

Un Saludo

**Comment by jormaral** [comment]
Buenos días.

En el archivo de descarga Consola_V2.0.zip no hay una carpeta Software. 
Sólo están las carpetas BBDD, EJECUTABLES e INSTALACIÓN.

Un saludo.

**Comment by jormaral** [comment]
Lo confirmo y te digo, pero debería estar.

**Comment by jormaral** [comment]
Efectivamente, no está, te adjunto la versión correcta.

Supongo que lo subirán.

Un Saludo

**Comment by jormaral** [comment]
Buenos días David, Coral.

La carpeta Software se subió la semana pasada a la sección SCM de la Comunidad, por lo que puedes descargar de allí la versión de Geoserver.

Un saludo.

**Comment by jormaral** [comment]
He realizado nuevamente la instalación, con los archivos que están en la carpeta SOFTWARE y sigo teniendo el mismo problema con Geoserver.

El error en el log de JBoss es este: 
18:42:14,474 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/geoserver]](MSC service thread 1-2) Excepción enviando evento inicializado de contexto a instancia de escuchador de clase org.geoserver.GeoserverInitStartupListener: java.util.ServiceConfigurationError: javax.imageio.spi.ImageWriterSpi: Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageWriterSpi could not be instantiated: java.lang.IllegalArgumentException: vendorName == null!

Después aparece el error:
18:42:35,681 ERROR [org.apache.catalina.core.StandardContext](MSC service thread 1-2) Falló en arranque del Contexto [/geoserver] debido a errores previos

Y por último: 
18:42:44,938 ERROR [stderr](MSC service thread 1-2) at org.geoserver.GeoserverInitStartupListener.contextDestroyed(GeoserverInitStartupListener.java:231)

**Comment by jormaral** [comment]
Disculpa, no se copió completo el primer error. Es este:
18:42:14,474 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/geoserver]](MSC service thread 1-2) Excepción enviando evento inicializado de contexto a instancia de escuchador de clase org.geoserver.GeoserverInitStartupListener: java.util.ServiceConfigurationError: javax.imageio.spi.ImageWriterSpi: Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageWriterSpi could not be instantiated: java.lang.IllegalArgumentException: vendorName == null!
at java.util.ServiceLoader.fail(ServiceLoader.java:224) [:1.7.0_02]
at java.util.ServiceLoader.access$100(ServiceLoader.java:181) [:1.7.0_02]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:370) [:1.7.0_02]
at java.util.ServiceLoader$1.next(ServiceLoader.java:438) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138) [:1.7.0_02]
at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159) [:1.7.0_02]
at org.geotools.image.io.ImageIOExt.allowNativeCodec(ImageIOExt.java:170) [gt-coverage-2.7.4.jar:]
at org.geoserver.GeoserverInitStartupListener.contextInitialized(GeoserverInitStartupListener.java:117) [main-2.1.3.jar:]
at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3368) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
at org.apache.catalina.core.StandardContext.start(StandardContext.java:3821) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:70) [jboss-as-web-7.0.2.Final.jar:7.0.2.Final]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1824)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1759)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [:1.7.0_02]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [:1.7.0_02]
at java.lang.Thread.run(Thread.java:722) [:1.7.0_02]
Caused by: java.lang.IllegalArgumentException: vendorName == null!
at javax.imageio.spi.IIOServiceProvider.<init>(IIOServiceProvider.java:76) [:1.7.0_02]
at javax.imageio.spi.ImageReaderWriterSpi.<init>(ImageReaderWriterSpi.java:231) [:1.7.0_02]
at javax.imageio.spi.ImageWriterSpi.<init>(ImageWriterSpi.java:213) [:1.7.0_02]
at com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageWriterSpi.<init>(CLibJPEGImageWriterSpi.java:84) [jai_imageio-1.1.jar:]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [:1.7.0_02]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [:1.7.0_02]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [:1.7.0_02]
at java.lang.reflect.Constructor.newInstance(Constructor.java:525) [:1.7.0_02]
at java.lang.Class.newInstance0(Class.java:372) [:1.7.0_02]
at java.lang.Class.newInstance(Class.java:325) [:1.7.0_02]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:362) [:1.7.0_02]
... 14 more

**Comment by jormaral** [comment]
Hemos vuelto a revisar el archivo de Geoserver que está en la carpeta Software de la sección SCM, pero es extraño que no te funcione con el que estaba antes, o con el que te pasó David Zazo. Por favor, prueba otra vez y nos comentas. 

Un saludo.

**Comment by jormaral** [comment]
Buenos días José.

He realizado nuevamente la instalación, desde cero, y sigue sin arrancar el Geoserver. 
Me le descargué el otro día del SCM, como me dijisteis. 

Adjunto el log que genera el geoserver cuando le habilito en el JBoss. 
Adjunto también los pasos que he seguido para su configuración en el sistema, sacados del manual URBR-CON_2011_12_Manual_Instalacion_v006.

Muchas gracias.
Un saludo.

[Jboss enable geoserver.txt](https://github.com/jormaral/urbanismo/files/191664/Jboss.enable.geoserver.txt)

**Comment by jormaral** [comment]
Adjunto el documento con los pasos realizados para la instalación y configuración del GeoServer.
[geoserver.docx](https://github.com/jormaral/urbanismo/files/191662/geoserver.docx)

**Comment by jormaral** [comment]
Vamos a revisar el error que nos mandabas y el documento que adjuntas, pero con ese Geoserver y el manual es como realizamos nosotros las implantaciones, por lo que debería funcionar. Si revisando la documentación que adjuntas detectamos algo raro te lo comentaremos.

Un saludo.

**Comment by jormaral** [comment]
Tampoco puedo desplegar geoserver. Me pasa exactamente lo mismo, los mismos errores.

¿Tenéis ya una solución a esto?

**Comment by jormaral** [comment]
Buenas Tardes Pablo,

Puedes facilitar el log de geoserver y lo revisamos. Siguiendo el documento de instalación se despliega correctamente el geoserver.

Un saludo

**Comment by jormaral** [comment]
El Geoserver no me genera log, pero si el Jboss al desplegar el geoserver.war.

[server.docx](https://github.com/jormaral/urbanismo/files/191683/server.docx)

**Comment by jormaral** [comment]
Tengo problemas con imageio, aquí esta el log.

[Uploading server1.docx…]()
